### ISSUE TITLE
Oprava překladu "Odlehčení nákladu"

### ISSUE THREAD

**Issue by Polarni** [Bladesheng/prison-architect-czech-translation#11]
https://github.com/Bladesheng/prison-architect-czech-translation/blob/39aac65bdb0134ff86d5c29b8912d9877f6dc46a/english-original-files/base-language.txt#L3618C41-L3618C60

Tohle bych přeložil spíše jako "_Zlehčení břemene_" nebo "_Snížení zátěže_".

**Comment by Bladesheng** [comment]
Opraveno. Díky 👍
